GET http://localhost:3003/users
Content-Type: application/json

###

GET http://localhost:3003/users?type=admin
Content-Type: application/json

###

GET http://localhost:3003/users/Alice
Content-Type: application/json

###

POST http://localhost:3003/users
Content-Type: application/json

 {
     "name": "Jhordan",
     "email": "jhordan.eu@gamil.com",
     "type": "ADMIN",
     "age": 19
 }